export const metadata = {
    title: 'Thakur',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
        
          {children}
          <h3> Nested Layout</h3>
        </body>
      </html>
    )
  }
  