export const metadata = {
  title: 'Thakur',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-500 p-1.5">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-green-500 p-1.5">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
